name: 'Setup Environment'
description: 'Sets up Node.js and installs dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: |
        npm ci
        npm install --global vercel@latest
